version: '3.1'

services:
  postgress:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_HOST: aluguelquadra
    ports:
      - 5432:5432